name: Question
description: Ask a question about using or contributing to the project
title: "Question: "
labels: ["Type: Question", "Needs Triage"]
body:
  - type: markdown
    attributes:
      value: |
        Issues on GitHub are intended to be related to bugs or feature requests, so we recommend using our other community resources instead of asking here.
        - Any other questions can be asked in the community [Discord Server](https://discord.gg/GMvrvjtvPr)
  - type: textarea
    id: question
    attributes:
      label: Question
    validations:
      required: true